env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: off
  react/style-prop-object: off
  no-restricted-exports: off
  react/prop-types: off
  react/jsx-props-no-spreading: off
